import { ModeConfig } from './types';

export const MODE_CONFIGS: ModeConfig[] = [
  {
    id: 'standard',
    label: 'Standard',
    description: 'Balanced daily routine with all sections',
    command: 'mode.standard()',
    color: '#00FF9F',
    visibleSections: ['morning', 'deep_work', 'wind_down'],
    presetHabits: [
      { name: 'Wake up at 6:00 AM', type: 'boolean', section: 'morning', color: '#FFB800', order: 0, schedule: [], archived: false },
      { name: 'Cold shower', type: 'boolean', section: 'morning', color: '#FFB800', order: 1, schedule: [], archived: false },
      { name: 'Meditate', type: 'timer', section: 'morning', color: '#FFB800', targetMinutes: 15, order: 2, schedule: [], archived: false },
      { name: 'Journal', type: 'boolean', section: 'morning', color: '#FFB800', order: 3, schedule: [], archived: false },
      { name: 'Read 20 pages', type: 'count', section: 'morning', color: '#FFB800', targetCount: 20, order: 4, schedule: [], archived: false },
      { name: 'Code 2 hours', type: 'timer', section: 'deep_work', color: '#00B4FF', targetMinutes: 120, order: 0, schedule: [1,2,3,4,5], archived: false },
      { name: 'Ship 1 feature', type: 'boolean', section: 'deep_work', color: '#00B4FF', order: 1, schedule: [1,2,3,4,5], archived: false },
      { name: 'Review PRs', type: 'boolean', section: 'deep_work', color: '#00B4FF', order: 2, schedule: [1,2,3,4,5], archived: false },
      { name: 'Learn something new', type: 'boolean', section: 'deep_work', color: '#00B4FF', order: 3, schedule: [], archived: false },
      { name: 'No screens after 10 PM', type: 'negative', section: 'wind_down', color: '#A855F7', order: 0, schedule: [], archived: false },
      { name: 'Stretch / Yoga', type: 'boolean', section: 'wind_down', color: '#A855F7', order: 1, schedule: [], archived: false },
      { name: 'Plan tomorrow', type: 'boolean', section: 'wind_down', color: '#A855F7', order: 2, schedule: [], archived: false },
      { name: 'Gratitude log', type: 'boolean', section: 'wind_down', color: '#A855F7', order: 3, schedule: [], archived: false },
    ],
  },
  {
    id: 'minimal',
    label: 'Minimal',
    description: 'Only the essentials — 5 core habits',
    command: 'mode.minimal()',
    color: '#6B6B80',
    visibleSections: ['morning', 'deep_work', 'wind_down'],
    presetHabits: [
      { name: 'Wake up early', type: 'boolean', section: 'morning', color: '#FFB800', order: 0, schedule: [], archived: false },
      { name: 'Exercise 30 min', type: 'timer', section: 'morning', color: '#FFB800', targetMinutes: 30, order: 1, schedule: [], archived: false },
      { name: 'Deep work block', type: 'timer', section: 'deep_work', color: '#00B4FF', targetMinutes: 120, order: 0, schedule: [1,2,3,4,5], archived: false },
      { name: 'Read', type: 'boolean', section: 'wind_down', color: '#A855F7', order: 0, schedule: [], archived: false },
      { name: 'Sleep by 11 PM', type: 'boolean', section: 'wind_down', color: '#A855F7', order: 1, schedule: [], archived: false },
    ],
  },
  {
    id: 'focus',
    label: 'Focus',
    description: 'Single-task deep focus sessions',
    command: 'mode.focus()',
    color: '#FFB800',
    visibleSections: ['morning', 'deep_work'],
    presetHabits: [
      { name: 'Morning clarity ritual', type: 'boolean', section: 'morning', color: '#FFB800', order: 0, schedule: [], archived: false },
      { name: 'Define #1 priority', type: 'boolean', section: 'morning', color: '#FFB800', order: 1, schedule: [], archived: false },
      { name: 'No social media', type: 'negative', section: 'morning', color: '#FFB800', order: 2, schedule: [], archived: false },
      { name: 'Deep focus — 90 min block', type: 'timer', section: 'deep_work', color: '#00B4FF', targetMinutes: 90, order: 0, schedule: [1,2,3,4,5], archived: false },
      { name: 'Deep focus — 2nd block', type: 'timer', section: 'deep_work', color: '#00B4FF', targetMinutes: 90, order: 1, schedule: [1,2,3,4,5], archived: false },
      { name: 'Review & reflect', type: 'boolean', section: 'deep_work', color: '#00B4FF', order: 2, schedule: [1,2,3,4,5], archived: false },
    ],
  },
  {
    id: 'deep_work',
    label: 'Deep Work',
    description: 'Cal Newport-inspired maker schedule',
    command: 'mode.deepwork()',
    color: '#00B4FF',
    visibleSections: ['morning', 'deep_work', 'wind_down'],
    presetHabits: [
      { name: 'No email before noon', type: 'negative', section: 'morning', color: '#FFB800', order: 0, schedule: [1,2,3,4,5], archived: false },
      { name: 'Plan deep work blocks', type: 'boolean', section: 'morning', color: '#FFB800', order: 1, schedule: [1,2,3,4,5], archived: false },
      { name: 'Block 1: Build', type: 'timer', section: 'deep_work', color: '#00B4FF', targetMinutes: 120, order: 0, schedule: [1,2,3,4,5], archived: false },
      { name: 'Block 2: Create', type: 'timer', section: 'deep_work', color: '#00B4FF', targetMinutes: 120, order: 1, schedule: [1,2,3,4,5], archived: false },
      { name: 'Block 3: Learn', type: 'timer', section: 'deep_work', color: '#00B4FF', targetMinutes: 60, order: 2, schedule: [1,2,3,4,5], archived: false },
      { name: 'Ship something', type: 'boolean', section: 'deep_work', color: '#00B4FF', order: 3, schedule: [1,2,3,4,5], archived: false },
      { name: 'Daily review', type: 'boolean', section: 'wind_down', color: '#A855F7', order: 0, schedule: [1,2,3,4,5], archived: false },
      { name: 'No work after 6 PM', type: 'negative', section: 'wind_down', color: '#A855F7', order: 1, schedule: [1,2,3,4,5], archived: false },
    ],
  },
  {
    id: 'study',
    label: 'Study',
    description: 'Optimized for learning & retention',
    command: 'mode.study()',
    color: '#A855F7',
    visibleSections: ['morning', 'deep_work', 'wind_down'],
    presetHabits: [
      { name: 'Review flashcards', type: 'boolean', section: 'morning', color: '#FFB800', order: 0, schedule: [], archived: false },
      { name: 'Read textbook — 30 pages', type: 'count', section: 'morning', color: '#FFB800', targetCount: 30, order: 1, schedule: [], archived: false },
      { name: 'Pomodoro session 1', type: 'timer', section: 'deep_work', color: '#00B4FF', targetMinutes: 50, order: 0, schedule: [], archived: false },
      { name: 'Pomodoro session 2', type: 'timer', section: 'deep_work', color: '#00B4FF', targetMinutes: 50, order: 1, schedule: [], archived: false },
      { name: 'Pomodoro session 3', type: 'timer', section: 'deep_work', color: '#00B4FF', targetMinutes: 50, order: 2, schedule: [], archived: false },
      { name: 'Practice problems', type: 'boolean', section: 'deep_work', color: '#00B4FF', order: 3, schedule: [], archived: false },
      { name: 'Teach / explain concept', type: 'boolean', section: 'wind_down', color: '#A855F7', order: 0, schedule: [], archived: false },
      { name: 'Review notes', type: 'boolean', section: 'wind_down', color: '#A855F7', order: 1, schedule: [], archived: false },
    ],
  },
  {
    id: 'fitness',
    label: 'Fitness',
    description: 'Training, nutrition & recovery',
    command: 'mode.fitness()',
    color: '#FF6B2C',
    visibleSections: ['morning', 'deep_work', 'wind_down'],
    presetHabits: [
      { name: 'Morning stretch — 10 min', type: 'timer', section: 'morning', color: '#FFB800', targetMinutes: 10, order: 0, schedule: [], archived: false },
      { name: 'Protein breakfast', type: 'boolean', section: 'morning', color: '#FFB800', order: 1, schedule: [], archived: false },
      { name: 'Drink 3L water', type: 'count', section: 'morning', color: '#FFB800', targetCount: 12, order: 2, schedule: [], archived: false },
      { name: 'Workout — strength', type: 'timer', section: 'deep_work', color: '#00B4FF', targetMinutes: 60, order: 0, schedule: [1,3,5], archived: false },
      { name: 'Workout — cardio', type: 'timer', section: 'deep_work', color: '#00B4FF', targetMinutes: 30, order: 1, schedule: [2,4,6], archived: false },
      { name: 'Track macros', type: 'boolean', section: 'deep_work', color: '#00B4FF', order: 2, schedule: [], archived: false },
      { name: 'No junk food', type: 'negative', section: 'wind_down', color: '#A855F7', order: 0, schedule: [], archived: false },
      { name: 'Sleep 8 hours', type: 'boolean', section: 'wind_down', color: '#A855F7', order: 1, schedule: [], archived: false },
      { name: '10 min foam roll', type: 'timer', section: 'wind_down', color: '#A855F7', targetMinutes: 10, order: 2, schedule: [], archived: false },
    ],
  },
  {
    id: 'monk',
    label: 'Monk',
    description: 'Maximum discipline — no excuses',
    command: 'mode.monk()',
    color: '#22D3EE',
    visibleSections: ['morning', 'deep_work', 'wind_down'],
    presetHabits: [
      { name: 'Wake at 5:00 AM', type: 'boolean', section: 'morning', color: '#FFB800', order: 0, schedule: [], archived: false },
      { name: 'Cold shower', type: 'boolean', section: 'morning', color: '#FFB800', order: 1, schedule: [], archived: false },
      { name: 'Meditate — 30 min', type: 'timer', section: 'morning', color: '#FFB800', targetMinutes: 30, order: 2, schedule: [], archived: false },
      { name: 'Journal — 3 pages', type: 'count', section: 'morning', color: '#FFB800', targetCount: 3, order: 3, schedule: [], archived: false },
      { name: 'Exercise — 60 min', type: 'timer', section: 'morning', color: '#FFB800', targetMinutes: 60, order: 4, schedule: [], archived: false },
      { name: 'Read — 50 pages', type: 'count', section: 'morning', color: '#FFB800', targetCount: 50, order: 5, schedule: [], archived: false },
      { name: 'Deep work — 4 hours', type: 'timer', section: 'deep_work', color: '#00B4FF', targetMinutes: 240, order: 0, schedule: [], archived: false },
      { name: 'Learn new skill — 1 hr', type: 'timer', section: 'deep_work', color: '#00B4FF', targetMinutes: 60, order: 1, schedule: [], archived: false },
      { name: 'No social media', type: 'negative', section: 'deep_work', color: '#00B4FF', order: 2, schedule: [], archived: false },
      { name: 'No alcohol', type: 'negative', section: 'wind_down', color: '#A855F7', order: 0, schedule: [], archived: false },
      { name: 'No screens after 9 PM', type: 'negative', section: 'wind_down', color: '#A855F7', order: 1, schedule: [], archived: false },
      { name: 'Gratitude log', type: 'boolean', section: 'wind_down', color: '#A855F7', order: 2, schedule: [], archived: false },
      { name: 'Plan tomorrow', type: 'boolean', section: 'wind_down', color: '#A855F7', order: 3, schedule: [], archived: false },
      { name: 'Sleep by 10 PM', type: 'boolean', section: 'wind_down', color: '#A855F7', order: 4, schedule: [], archived: false },
    ],
  },
  {
    id: 'detox',
    label: 'Detox',
    description: 'Digital & dopamine detox — reset your brain',
    command: 'mode.detox()',
    color: '#FF4444',
    visibleSections: ['morning', 'deep_work', 'wind_down'],
    presetHabits: [
      { name: 'No phone first hour', type: 'negative', section: 'morning', color: '#FFB800', order: 0, schedule: [], archived: false },
      { name: 'Walk outside — 20 min', type: 'timer', section: 'morning', color: '#FFB800', targetMinutes: 20, order: 1, schedule: [], archived: false },
      { name: 'Mindful breakfast', type: 'boolean', section: 'morning', color: '#FFB800', order: 2, schedule: [], archived: false },
      { name: 'No social media', type: 'negative', section: 'deep_work', color: '#00B4FF', order: 0, schedule: [], archived: false },
      { name: 'No YouTube / Netflix', type: 'negative', section: 'deep_work', color: '#00B4FF', order: 1, schedule: [], archived: false },
      { name: 'No news browsing', type: 'negative', section: 'deep_work', color: '#00B4FF', order: 2, schedule: [], archived: false },
      { name: 'Read physical book', type: 'boolean', section: 'deep_work', color: '#00B4FF', order: 3, schedule: [], archived: false },
      { name: 'No screens after 8 PM', type: 'negative', section: 'wind_down', color: '#A855F7', order: 0, schedule: [], archived: false },
      { name: 'Journaling', type: 'boolean', section: 'wind_down', color: '#A855F7', order: 1, schedule: [], archived: false },
      { name: 'Meditation — 15 min', type: 'timer', section: 'wind_down', color: '#A855F7', targetMinutes: 15, order: 2, schedule: [], archived: false },
    ],
  },
  {
    id: 'recovery',
    label: 'Recovery',
    description: 'Gentle restart — no pressure, rebuild slowly',
    command: 'mode.recovery()',
    color: '#22C55E',
    visibleSections: ['morning', 'wind_down'],
    presetHabits: [
      { name: 'Get out of bed', type: 'boolean', section: 'morning', color: '#FFB800', order: 0, schedule: [], archived: false },
      { name: 'Drink water', type: 'boolean', section: 'morning', color: '#FFB800', order: 1, schedule: [], archived: false },
      { name: 'Eat a real meal', type: 'boolean', section: 'morning', color: '#FFB800', order: 2, schedule: [], archived: false },
      { name: 'Go outside — even briefly', type: 'boolean', section: 'wind_down', color: '#A855F7', order: 0, schedule: [], archived: false },
      { name: 'Do one small task', type: 'boolean', section: 'wind_down', color: '#A855F7', order: 1, schedule: [], archived: false },
      { name: 'Be kind to yourself', type: 'boolean', section: 'wind_down', color: '#A855F7', order: 2, schedule: [], archived: false },
    ],
  },
  {
    id: 'custom',
    label: 'Custom',
    description: 'Start empty — build your own routine',
    command: 'mode.custom()',
    color: '#E8E8ED',
    visibleSections: ['morning', 'deep_work', 'wind_down', 'custom'],
    presetHabits: [],
  },
];

export function getModeConfig(id: string): ModeConfig {
  return MODE_CONFIGS.find(m => m.id === id) || MODE_CONFIGS[0];
}
